%YAML:1.0
die-id: 0 
#Number of rows in the grid output
rows: 5
#Number columns rows in the grid output
columns: 5
#Width of the output picture
width: 3840
#Height of the output picture
height: 2160
#Format of the output picture
output-format: nv12
#stride align of the output picture
stride-align: 1 
#output buffer pool size
poolsize: 30
dump: false
text-pic-path: dataset/gridbg/0303_ari_100_2560_360.yuv
text-pic-width: 2560
text-pic-height: 360
specialrect:
  color: [255,255,0]
  rectnum: 4
  rowarray: [1,2,1,2]
  colarray: [1,1,2,2]


#####0
