add_subdirectory(queueElement)
add_subdirectory(muxElement)
add_subdirectory(avDemuxElement)
add_subdirectory(vdecElement)
add_subdirectory(vencElement)
add_subdirectory(preProcessElement)
add_subdirectory(inferElement)
add_subdirectory(postprocessElement)
add_subdirectory(osdElement)
add_subdirectory(videoGridElement)
add_subdirectory(videosinkElement)
add_subdirectory(fileSinkElement)
add_subdirectory(trackerElement)
add_subdirectory(demuxElement)
add_subdirectory(teeElement)
add_subdirectory(v4l2SrcElement)
add_subdirectory(testSrcElement)
add_subdirectory(testSinkElement)
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/openvoElement/CMakeLists.txt)
  add_subdirectory(openvoElement)
else()
  message(STATUS "openvoElement source not found; skipping target")
endif()
