# RISC-V 64-bit Linux cross-compilation toolchain.
#
# Usage:
#   cmake -S src -B build-riscv64 \
#     -DCMAKE_TOOLCHAIN_FILE=cmake/riscv64-toolchain.cmake

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_SYSROOT "/opt/riscv/sysroot" CACHE PATH "RISC-V sysroot")
set(CMAKE_STAGING_PREFIX "${CMAKE_INSTALL_PREFIX}" CACHE PATH "RISC-V staging prefix")

set(_RISCV_TOOLCHAIN_ROOT "/opt/riscv" CACHE PATH "RISC-V toolchain root")
set(_RISCV_TOOLCHAIN_PREFIX "riscv64-unknown-linux-gnu" CACHE STRING "RISC-V compiler prefix")

set(CMAKE_C_COMPILER "${_RISCV_TOOLCHAIN_ROOT}/bin/${_RISCV_TOOLCHAIN_PREFIX}-gcc" CACHE FILEPATH "RISC-V C compiler")
set(CMAKE_CXX_COMPILER "${_RISCV_TOOLCHAIN_ROOT}/bin/${_RISCV_TOOLCHAIN_PREFIX}-g++" CACHE FILEPATH "RISC-V C++ compiler")

set(_RISCV_SYSROOT_MULTIARCH_INCLUDE "${CMAKE_SYSROOT}/usr/include/riscv64-linux-gnu")
set(_RISCV_SYSROOT_MULTIARCH_LIB "${CMAKE_SYSROOT}/usr/lib/riscv64-linux-gnu")
set(_RISCV_SYSROOT_USR_LIB "${CMAKE_SYSROOT}/usr/lib")
set(_RISCV_SYSROOT_LIB "${CMAKE_SYSROOT}/lib")

set(_RISCV_RPATH_LINK_FLAGS
    "-Wl,-rpath-link,${_RISCV_SYSROOT_MULTIARCH_LIB} -Wl,-rpath-link,${_RISCV_SYSROOT_USR_LIB} -Wl,-rpath-link,${_RISCV_SYSROOT_LIB}"
)

set(CMAKE_C_FLAGS_INIT "-isystem ${_RISCV_SYSROOT_MULTIARCH_INCLUDE}")
set(CMAKE_CXX_FLAGS_INIT "-isystem ${_RISCV_SYSROOT_MULTIARCH_INCLUDE}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-B${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_USR_LIB} ${_RISCV_RPATH_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-B${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_USR_LIB} ${_RISCV_RPATH_LINK_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-B${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_MULTIARCH_LIB} -L${_RISCV_SYSROOT_USR_LIB} ${_RISCV_RPATH_LINK_FLAGS}")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

find_program(PKG_CONFIG_EXECUTABLE
    NAMES pkg-config pkgconf
    NO_CMAKE_FIND_ROOT_PATH
)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig:${CMAKE_SYSROOT}/usr/lib/riscv64-linux-gnu/pkgconfig"
)
